name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mateusmagalhaes/devops_project:$(date +%s)
    - name: push the docker image to Hub
      run: docker push mateusmagalhaes/devops_project
